### ISSUE TITLE
Dark Mode bug with (High) Sierra "Dark Menubar & Dock" setting

### ISSUE THREAD

**Issue by raxelbrof** [dyerc/Doughnut#23]
Assuming this is the issue, as it seems to catch a few developers out - Pre-Mojave has a "Dark Menubar & Dock" setting, that is not the same as Mojave & Onwards' Dark Mode.

Screenshot attached

![darkbug](https://user-images.githubusercontent.com/64583201/80693080-da398c00-8b15-11ea-8ff0-3dd3e0ea3b1b.png)

**Comment by dyerc** [comment]
Hi @raxelbrof, sorry it has taken me a few weeks to get back to you about this. I know that dark mode in Catalina works correctly in Doughnut (ie. all components are styled correctly in the dark colouring). I don't have any machines still running High Sierra in order to debug further so unfortunately I think I will need to close this issue. If anyone out there would like to debug further please by all means comment and we can re-open this issue. Sorry there is nothing more helpful I can suggest.

**Comment by raxelbrof** [comment]
If there's something I can do to help debug it, please let me know. FYI a similar issue to this was solved for a menubar app not showing the correct icon for Sierra / High Sierra, by (paraphrasing the developer) substituting a hardcoded image, for a template image, which caused the system to sort it out.

If auto-switching isn't something you can debug, can it be made a 3 choice user-overide, eg: System Theme / Light Mode / Dark Mode?

**Comment by dyerc** [comment]
At the moment Doughnut doesn't really have a theming system so to speak. It lets the builtin components figure out themselves whether to show a dark or light style. Any custom components do manually have two themes.

Since lots of the "theming" is handled by MacOS I'm not sure what would be feasible on older versions without the dark mode that's present in Mojave onwards. It might be a matter of building a theming system which would be quite a sizeable undertaking. The News Explorer app you mention must have more of an inbuilt theme system.

Sorry not to be able to provide anything more helpful.

**Comment by dyerc** [comment]
The only other thing that might be helpful, you could try version 1.0.2: https://github.com/dyerc/Doughnut/releases/download/v1.0.2/Doughnut-1.0.2.dmg which didn't have dark mode and see if this is more usable on older versions of MacOS.
